# ---------------------------------------------------------------------------
# aggregate.py
# Author:  jdburrou Jon Burroughs
# Created on: 2012-01-14 08:53:01.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: aggregate <inputFeatures> <aggDistance> <outputFeatures> <outputTable> 
# Description:
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo

# Import arcpy module
import arcpy

# Default base directory
baseDir = "C:\\Temp\\export_example"

# Input arguments
inputFeatures = arcpy.GetParameterAsText(0)
if inputFeatures == '#' or not inputFeatures:
    inputFeatures = baseDir + "\\COVER63p.shp" # provide a default value if unspecified

aggDistance = arcpy.GetParameterAsText(1)
if aggDistance == '#' or not aggDistance:
    aggDistance = "10 Feet" # provide a default value if unspecified

# Label for output files
aggDistanceLabel = aggDistance.replace(" ", "_")   

# Output arguments
outputFeatures = arcpy.GetParameterAsText(2)
if outputFeatures == '#' or not outputFeatures:
    outputFeatures = baseDir + "\\COVER63p_AggregatePolygons_" + aggDistanceLabel # provide a default value if unspecified

outputTable = arcpy.GetParameterAsText(3)
if outputTable == '#' or not outputTable:
    outputTable = baseDir + "\\COVER63p_AggregatePolygons_" + aggDistanceLabel + "_Tbl" # provide a default value if unspecified

# Process: Aggregate Polygons
arcpy.AggregatePolygons_cartography(inputFeatures, outputFeatures, aggDistance, "0 Unknown", "0 Unknown", "NON_ORTHOGONAL")

